- hosts: localhost
  become: yes
  gather_facts: false
  tasks:
  - name: Create a directory if it does not exist
    file:
      path: "/home/collect_logs/results"
      state: directory
      mode: '0755'
  
- hosts: all
  become: yes
  tasks:
  - name: Get log file
    fetch:
      src: "{{ item }}"
      dest: /home/collect_logs/results/
    loop: 
      - "/var/log/syslog"
      - "/var/log/kern.log"
      - "/var/log/auth.log"
      


